### ISSUE TITLE
texbuild gives printing error

### ISSUE THREAD

**Issue by onaret** [pbiggar/texbuild#2]
When I run texbuild on a file.tex

`texbuild file.tex
`

It output

> File "/usr/bin/texbuild", line 45
>     print str(time.strftime("%H:%M:%S")) + " - " + message
>             ^
> SyntaxError: invalid syntax

**Comment by pbiggar** [comment]
I would guess you're using python3. This was written in python 2, and print is one of the things that has changed.

**Comment by onaret** [comment]
Thank you for your help. 
I forgot about this issue. I haven' t used texbuild in the end but it is obviously what was wrong.
